"""Snapshot loading helpers used by API endpoints and cron tasks."""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, Optional

from sqlalchemy.orm import Session

from src.core.config_loader import get_base_dir
from src.db.models import Snapshot

logger = logging.getLogger(__name__)

DEFAULT_SNAPSHOT_NAME = "btc_snapshot.json"


def _load_snapshot_file(path: Path) -> Optional[Dict[str, Any]]:
    if not path.exists():
        return None
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as exc:  # pragma: no cover - defensive logging
        logger.warning("snapshot_builder: failed to load %s: %s", path, exc)
        return None


def _normalize_snapshot(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Bring snapshot JSON to the shape expected by API consumers."""
    snapshot = dict(payload) if isinstance(payload, dict) else {}
    snapshot.setdefault("symbol", "BTCUSDT")

    timestamp = snapshot.get("timestamp")
    if timestamp and "timestamp_iso" not in snapshot:
        snapshot["timestamp_iso"] = timestamp

    if "timeframes" not in snapshot:
        candles = snapshot.get("candles")
        if isinstance(candles, dict):
            timeframes = {}
            for tf, candle in candles.items():
                if not isinstance(candle, dict):
                    continue
                timeframes[tf] = {
                    "last_open": candle.get("open"),
                    "last_high": candle.get("high"),
                    "last_low": candle.get("low"),
                    "last_close": candle.get("close"),
                    "open_time": candle.get("open_time"),
                    "close_time": candle.get("close_time"),
                }
            if timeframes:
                snapshot["timeframes"] = timeframes

    return snapshot


def _load_latest_db_snapshot(db: Session) -> Optional[Dict[str, Any]]:
    if db is None:
        return None
    row = (
        db.query(Snapshot)
        .order_by(Snapshot.created_at.desc())
        .first()
    )
    if row is None:
        return None
    return _normalize_snapshot(row.payload or {})


def build_btc_snapshot(db: Session, *, snapshot_path: Optional[Path] = None) -> Dict[str, Any]:
    """
    Returns the most recent BTC snapshot.

    1. Tries to read the latest snapshot stored in the DB (snapshots table).
    2. Falls back to data/btc_snapshot.json (generated by cron/CLI).
    3. Raises ValueError if nothing is available.
    """

    snapshot = _load_latest_db_snapshot(db)
    if snapshot:
        return snapshot

    base_dir = get_base_dir()
    path = snapshot_path or (base_dir / "data" / DEFAULT_SNAPSHOT_NAME)
    snapshot_file = _load_snapshot_file(path)
    if snapshot_file:
        return _normalize_snapshot(snapshot_file)

    raise ValueError("No BTC snapshot available in DB or data directory")


def persist_snapshot(db: Session, payload: Dict[str, Any]) -> Snapshot:
    snapshot = Snapshot(symbol=payload.get("symbol", "BTCUSDT"), payload=_normalize_snapshot(payload))
    db.add(snapshot)
    db.commit()
    db.refresh(snapshot)
    return snapshot
